diff --git a/Makefile b/Makefile
index 5f9f308..21c6f2e 100644
--- a/Makefile
+++ b/Makefile
@@ -1,10 +1,20 @@
-CC=$(CROSS_COMPILE)gcc
+bindir ?= /usr/bin
+
+CC ?= $(CROSS_COMPILE)gcc
+
 CFLAGS+=-D_GNU_SOURCE -std=c99
 
-all: btflash2
+PROG = btflash2
+OBJS = btflash2.o
+
+all: $(PROG)
 
 btflash2.o: btflash2.c spi.h spi_regs.h
 
+install:
+	install -d -D -m 755 ${DESTDIR}${bindir}
+	install -m 755 $(PROG) ${DESTDIR}${bindir}
+
 clean:
-	rm *.o btflash2
+	rm -f $(OBJS) $(PROG)
 
