#!/bin/sh
# Copyright (C) 2018 T-platforms JSC.
# Licensed under GPL-v2

initfs_enabled() {
	return 0
}

initfs_run() {
	if [ "$bootparam_root" != "initfs" ]; then
		return
	fi

	if [ -f "/sbin/init" ]; then

		msg ""
		msg "Starting system init at initramfs."

		rm -rf $ROOTFS_DIR $MODULES_DIR /init

		msg "Waiting 5 more seconds for kernel to finish booting."

		sleep 5

		exec /sbin/init
	else
		fatal "System init file doesn't exist"
	fi
}
